version: '3.7'
services:
  server_service:
    depends_on:
      - 'mydb'
    build:
      context: .
    ports:
      - 8080:8080

  mydb:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: mydb